grafana:
  defaultDashboardsTimezone: Europe/Moscow
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
    - grafana.ruadmin24.ru
    tls:
    - secretName: ruadmin24-ru-tls
      hosts:
      - grafana.ruadmin24.ru

nodeExporter:
  enabled: true
  operatingSystems:
    linux:
      enabled: true
    aix:
      enabled: false
    darwin:
      enabled: false

