namespaceOverride: monitoring
global:
  defaultStorageClass: prometheus
server:
  retention: 20d
  persistence:
    enabled: true
    storageClass: prometheus
    size: 10Gi
  extraScrapeConfigs:
  - job_name: 'kube-state-metrics'
    static_configs:
    - targets: ['kube-state-metrics.monitoring.svc.cluster.local:8080']