namespaceOverride: monitoring
global:
  defaultStorageClass: prometheus
server:
  retention: 20d
  persistence:
    enabled: true
    storageClass: prometheus
    size: 10Gi
  extraScrapeConfigs:
    - job_name: 'kube-state-metrics'
      static_configs:
      - targets: ['kube-state-metrics.monitoring.svc.cluster.local:8080']
    - job_name: 'node-exporter'
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - source_labels: [__meta_kubernetes_endpoints_name]
        regex: 'node-exporter'
        action: keep
      - source_labels: [__meta_kubernetes_pod_node_name]
        target_label: instance